# Generated by Django 6.0.1 on 2026-01-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название чата'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
